### ISSUE TITLE
Error with try  login-matrix

### ISSUE THREAD

**Issue by raymand211092** [beeper/linkedin#28]
Traceback (most recent call last):
  File "/root/linkedin/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/root/linkedin/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/root/linkedin/lib/python3.9/site-packages/linkedin_matrix/commands/auth.py", line 186, in login_matrix
    _, homeserver = Client.parse_mxid(evt.sender.mxid)
AttributeError: type object 'Client' has no attribute 'parse_mxid'

**Comment by raymand211092** [comment]
Name: mautrix
Version 0.18.9

**Comment by sumnerevans** [comment]
I should really just update the bridge to use a newer mautrix version...

**Comment by sumnerevans** [comment]
Does `login-matrix` when you run `master` now?

**Comment by raymand211092** [comment]
Another error:

(linkedin) root@srv112118-206152:~/linkedin# python -m linkedin_matrix
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/linkedin/lib/python3.9/site-packages/linkedin_matrix/__main__.py", line 13, in <module>
    from .matrix import MatrixHandler
  File "/root/linkedin/lib/python3.9/site-packages/linkedin_matrix/matrix.py", line 22, in <module>
    from . import portal as po, user as u
  File "/root/linkedin/lib/python3.9/site-packages/linkedin_matrix/portal.py", line 82, in <module>
    MediaInfo = FileInfo | VideoInfo | AudioInfo | ImageInfo
TypeError: unsupported operand type(s) for |: 'ABCMeta' and 'ABCMeta'

**Comment by sumnerevans** [comment]
Try with Python 3.10?

**Comment by raymand211092** [comment]
When try with Python3.10 i have this error:
```
Traceback (most recent call last):
  File "/root/linkedin/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 86, in <module>
    from mautrix.crypto.attachments import encrypt_attachment
  File "/root/linkedin/lib/python3.10/site-packages/mautrix/crypto/attachments/__init__.py", line 1, in <module>
    from .async_attachments import (
  File "/root/linkedin/lib/python3.10/site-packages/mautrix/crypto/attachments/async_attachments.py", line 22, in <module>
    from .attachments import _get_decryption_info, _prepare_encryption, inplace_encrypt_attachment
  File "/root/linkedin/lib/python3.10/site-packages/mautrix/crypto/attachments/attachments.py", line 15, in <module>
    import unpaddedbase64
ModuleNotFoundError: No module named 'unpaddedbase64'
```
But i solved with `pip install unpaddedbase64`

And then working perfectly thanks
