### ISSUE TITLE
Error !!

### ISSUE THREAD

**Issue by raymand211092** [beeper/linkedin#3]
root@srv1885-206152:~/linkedin# python3.9 -m linkedin_matrix -g
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/linkedin/linkedin_matrix/__main__.py", line 3, in <module>
    from mautrix.bridge import Bridge
ModuleNotFoundError: No module named 'mautrix'

**Comment by raymand211092** [comment]
I have fixed this bug this way!!
cd /linkedin/linkedin_matrix
poetry shell
and run the other commands to install the missing dependencies
